// lib/server/serializers/balik-manggagawa.ts
// Field selection for BM clearance audit logs.

export const serializeBalikManggagawaClearance = (clearance: any) => ({
  id: clearance.id,
  control_number: clearance.control_number,
  name_of_worker: clearance.name_of_worker,
  sex: clearance.sex ?? null,
  employer: clearance.employer,
  destination: clearance.destination,
  position: clearance.position ?? null,
  months_years: clearance.months_years ?? null,
  with_principal: clearance.with_principal ?? null,
  new_principal_name: clearance.new_principal_name ?? null,
  employment_duration: clearance.employment_duration ?? null,
  date_arrival: clearance.date_arrival ?? null,
  date_departure: clearance.date_departure ?? null,
  place_date_employment: clearance.place_date_employment ?? null,
  employment_start_date: clearance.employment_start_date ?? null,
  processing_date: clearance.processing_date ?? null,
  date_blacklisting: clearance.date_blacklisting ?? null,
  total_deployed_ofws: clearance.total_deployed_ofws ?? null,
  reason_blacklisting: clearance.reason_blacklisting ?? null,
  years_with_principal: clearance.years_with_principal ?? null,
  remarks: clearance.remarks ?? null,
  clearance_type: clearance.clearance_type ?? null,
  status: clearance.status ?? null,
  evaluator: clearance.evaluator ?? null,
  salary: clearance.salary ?? null,
  raw_salary: clearance.raw_salary ?? null,
  salary_currency: clearance.salary_currency ?? null,
  job_type: clearance.job_type ?? null,
  deleted_at: clearance.deleted_at ?? null,
});

